[book]
title = "Naev Development Manual"
authors = ["Naev DevTeam"]
description = "This book covers different aspects of developing for Naev, not only limited to the main repository, but also for developing plugins for the Naev engine."
src = "src"
language = "en"

[rust]
edition = "2024"

[output.html]
git-repository-url = "https://codeberg.org/naev/naev"
git-repository-icon = "fa-code-fork"
edit-url-template = "https://codeberg.org/naev/naev/_edit/main/docs/manual/src/{path}"
