name = "engines"
display = "Engines"
description = "This slot is used for engines. Engines propel the ship, which is kind of important. Engines require energy from the core systems to function."
required = true
exclusive = true
icon = "engines"
tags = ["core", "engines"]
